sudo: required
services:
  - docker

before_install:
  - docker build -t castrorodrigo355/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true castrorodrigo355/docker-react npm run test